-- migrations/002_drop_student_memory.sql
-- Retire the cross-session "student memory" store.
--
-- Applied by `node scripts/migrate.mjs`, which records it in schema_migrations
-- so it runs at most once per database. Safe to re-run by hand: IF EXISTS
-- makes a second pass a no-op. The table's index (idx_memory_session) is
-- dropped with it on both drivers.
--
-- WHY: student_memory held free-text facts extracted from a (possibly
-- minor's) conversations and replayed them into later prompts. The feature is
-- being removed; its rows are personal data with no remaining reader, so the
-- table goes rather than lingering.
--
-- Bookkeeping only since 2026-09: db.initSchema runs the same
-- `DROP TABLE IF EXISTS student_memory` on EVERY server boot (both drivers),
-- inside Railway's network, so production no longer depends on anyone running
-- this file (a laptop `railway run` cannot reach the private Postgres
-- anyway). The boot-time drop also cleans up after a rollback to a
-- pre-removal build (whose initSchema recreates the table even though this
-- migration is already recorded) as soon as a current build boots again.
-- Running this file is still harmless: against a database a current server
-- has booted on, it is a no-op that just gets recorded.

DROP TABLE IF EXISTS student_memory;
