import CoreText
import Foundation

/// Registers the bundled reading fonts (DesignSystem/Sources/Fonts) with
/// CoreText so `Font.custom(_:)` can resolve them anywhere in the process —
/// app, previews, and the SPM test host alike.
///
/// Why programmatic registration instead of `UIAppFonts` in the app's
/// Info.plist: the plist is generated by xcodegen from project.yml (edits
/// there ripple through the generated project), `UIAppFonts` only works
/// inside the app bundle (not in previews or `swift test`), and the fonts
/// live in THIS package's resource bundle, which the plist key can't see.
///
/// Idempotent: registration runs once per process via a `static let`;
/// CoreText's "already registered" error (code 105) is treated as success so
/// hot-reloads and previews can re-run it safely.
public enum BrandFontRegistrar {
    /// Ensure the bundled faces are registered. Returns true when every
    /// bundled font is available (freshly registered or already present).
    @discardableResult
    public static func registerReadingFonts() -> Bool { registered }

    private static let registered: Bool = {
        let urls = Bundle.module.urls(forResourcesWithExtension: "ttf", subdirectory: "Fonts") ?? []
        guard !urls.isEmpty else { return false }
        var allOK = true
        for url in urls {
            var error: Unmanaged<CFError>?
            if !CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error) {
                // kCTFontManagerErrorAlreadyRegistered — success for our purposes.
                if let e = error?.takeRetainedValue(), CFErrorGetCode(e) != 105 {
                    allOK = false
                }
            }
        }
        return allOK
    }()
}
